name: dirtx
description: "DIRTX"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.2
  window_manager: ^0.5.1
  universal_platform: ^1.1.0
  http: ^1.5.0
  file_picker: ^10.2.3
  video_player: ^2.10.0
  video_player_macos: ^2.0.1
  chewie: ^1.12.1
  video_player_win: ^3.2.0
  mjpeg_stream: ^1.0.1
  path: ^1.9.1
  path_provider: ^2.1.5
  get_thumbnail_video: ^0.7.3
  fc_native_video_thumbnail: ^0.17.2
  flutter_launcher_icons: ^0.14.4


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: SpaceGrotesk
      fonts:
        - asset: assets/fonts/SpaceGrotesk-Light.ttf
          weight: 300
        - asset: assets/fonts/SpaceGrotesk-Regular.ttf
          weight: 400
        - asset: assets/fonts/SpaceGrotesk-Medium.ttf
          weight: 500
        - asset: assets/fonts/SpaceGrotesk-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/SpaceGrotesk-Bold.ttf
          weight: 700

flutter_launcher_icons:
  windows:
    generate: true
    image_path: "assets/icon/dirtx.png"
    icon_size: 256

pubspec:
  yaml:
